### ISSUE TITLE
Step Time Increase Leading to NCCL Timeout with FSDP2

### ISSUE THREAD

**Issue by xhwang22** [pytorch/torchtitan#1092]
**Description**
I am encountering an issue when using fsdp2 where step time significantly increases after a certain number of steps, leading to NCCL timeouts. Initially, each step takes around 2 seconds, as shown in the earlier logs. However, after reaching step 1800, most processes experience a noticeable increase in step time except for one. This behavior causes errors such as:
```
[rank3]:[E410 14:46:34.629385703 ProcessGroupNCCL.cpp:684] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E410 14:46:34.629438241 ProcessGroupNCCL.cpp:698] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E410 14:46:34.630696293 ProcessGroupNCCL.cpp:1896] [PG ID 0 PG GUID 0(default_pg) Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=319682, OpType=_ALLGATHER_BASE, NumelIn=65667328, NumelOut=525338624, Timeout(ms)=100000) ran for 138169 milliseconds before timing out.
```

The discrepancy in step time across processes seems to result in the NCCL operations timing out.

**Observations**
At earlier steps (e.g., step 10), the step time is approximately 2.5 seconds across all processes.

By later steps  (e.g., step 1800), most processes experience longer step times except for one process, leading to the timeout error.

My training configuration (in TOML) is as follows:

```
[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"

[optimizer]
name = "AdamW"
lr = 1.5e-4

[training]
batch_size = 1
seq_len = 4096
warmup_steps = 2000
max_norm = 1.0
steps = 15000
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 15000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"
```

Are there any recommended solutions to solve this?

![Image](https://github.com/user-attachments/assets/7b22f8ef-d16b-497d-9689-ccbc0b15bf24)

![Image](https://github.com/user-attachments/assets/eabbb96e-5920-4410-b0a8-242fee7347f3)

**Comment by tianyu-l** [comment]
could you turn on `--metrics.enable_profiling` and see where time has been spent on across different steps? e.g. compare the profiler trace of step 10 and step 1000.

**Comment by xhwang22** [comment]
Thank you for the suggestion! I followed your advice and used the Torch profiler to compare the operation durations between steps 100 and 5000. Operations like `nccl._all_gather_base, record_param_comms, `and `cuLaunchKernelEx` show substantial duration increases. These are likely related to inter-GPU communication. Do you have recommendations for addressing these step time imbalances?  Alternatively, are there specific profiling metrics I should focus on to pinpoint the root cause? 
Thank you for your assistance!

![Image](https://github.com/user-attachments/assets/4ac56d78-1fea-4138-ae6a-5fe49d69cf3c)

**Comment by xhwang22** [comment]
@tianyu-l

**Comment by tianyu-l** [comment]
The default timeout during training is 100 seconds, according to `https://github.com/pytorch/torchtitan/blob/main/torchtitan/config_manager.py#L728`, which means unless the same collective happens within 100 seconds on all the devices, there shouldn't be timeout. In your case, am I interpreting correctly that some ranks take ~2 seconds to finish an iteration and some other take ~5 seconds? Or what is the unit of time in the profiler stats you shared?

> after reaching step 1800, most processes experience a noticeable increase in step time except for one

What is the one that doesn't see increase? Is it rank 0? What's your definition of "step time"?
I ask because I wonder if it's possible that this step is taking longer wall time, and other ranks are all waiting for this rank, but the way you calculate time takes "waiting time" into account, so it actually shows this special rank taking shorter than others waiting for it.

One thing rank 0 is different from other ranks is that by default, metrics logging only happens on rank 0. Is it possible that your TB log storage gets slower throughout time?

These are just random guesses, sorry if they don't make sense.

**Comment by xhwang22** [comment]
Thank you so much for your detailed suggestions and insights. After investigating the issue further, I checked the throughput and identified that the longer step time was indeed caused by rank 0 taking additional time for logging. This appears to have been due to the disk mount configuration.

I resolved the issue by changing the logging location, and the step times are now consistent across all ranks.

Thanks again for your help! I’ll be closing this issue as the problem has been resolved.
