### ISSUE TITLE
PP Stage init hangs on multi-nodes

### ISSUE THREAD

**Issue by rakkit** [pytorch/torchtitan#1492]
I have been struggling with this issue for some time, and I am not confident whether it is caused by our machine setup or bugs in PP.

We saw that when testing PP across multiple nodes, some rank hangs at the [_shape_inference](https://github.com/pytorch/pytorch/blob/v2.7.0/torch/distributed/pipelining/stage.py#L1328) during PP stage initialisation. 
On a single 4-GPU node, configurations such as (PP=1), (PP=2), or (PP=4) work without issue. 
The problem arises when running across two nodes—for example, _**only**_ with configurations like (FSDP=2, PP=4) or (FSDP=4, PP=2). In contrast, configurations like (PP=8) or sometimes (TP=4, PP=2) work without problem.

The immediate problem is that we cannot do DP/EP+PP for MoE training.

I suspect the problem comes from the multiple P2P communications across nodes (so I dont know if it's our system's problem or not, we have IB inter-nodes and NVLink intra-nodes). Sometimes it raises an error, connection cannot be built, sometimes it just hangs.   A possible workaround could be to explicitly define the input and output shapes during the PP stage construction (we can do this in torchtian).

The problem is still there for PyTorch 2.7.1/CUDA 12.8 + NCCL runtime 2.26.2

**Comment by tianyu-l** [comment]
@H-Huang @wconstab 
could you help take a look?

**Comment by H-Huang** [comment]
Hi @rakkit, thanks for flagging and sorry to hear you are hitting issues. Thats super interesting that PP=8 works but the other variations don't.

A couple of ideas that might help debug:

1) After the PP mesh is initialized can you run some P2P ops to force the initialization of NCCL communicators. If this hangs this will give us a better signal (and better reproducible script to debug). I have seen issues before when only part of NCCL communicators are initialized which causes issues, so maybe this could fix your issue. A script like this could work:

```python
    pp_rank = pp_mesh.get_local_rank()
    pp_size = pp_mesh.size()
    send_tensor = torch.arange(2, dtype=torch.bfloat16, device="cuda") + 2 * pp_rank

    def _setup_fwd():
        recv_tensor = torch.randn(2, dtype=torch.bfloat16, device="cuda")
        send_op = dist.P2POp(
            op=dist.isend,
            tensor=send_tensor,
            group=pp_mesh.get_group(),
            group_peer=(pp_rank + 1) % pp_size,
        )
        recv_op = dist.P2POp(
            op=dist.irecv,
            tensor=recv_tensor,
            group=pp_mesh.get_group(),
            group_peer=(pp_rank - 1 + pp_size) % pp_size,
        )
        reqs = dist.batch_isend_irecv([send_op, recv_op])
        for req in reqs:
            req.wait()

    def _setup_bwd():
        send_tensor = torch.arange(2, dtype=torch.bfloat16, device="cuda") + 2 * pp_rank
        recv_tensor = torch.randn(2, dtype=torch.bfloat16, device="cuda")
        send_op = dist.P2POp(
            op=dist.isend,
            tensor=send_tensor,
            group=pp_mesh.get_group(),
            group_peer=(pp_rank - 1 + pp_size) % pp_size,
        )
        recv_op = dist.P2POp(
            op=dist.irecv,
            tensor=recv_tensor,
            group=pp_mesh.get_group(),
            group_peer=(pp_rank + 1) % pp_size,
        )
        reqs = dist.batch_isend_irecv([send_op, recv_op])
        for req in reqs:
            req.wait()

    _setup_fwd()
    _setup_bwd()
```

2) Add environment variable `TORCH_LOGS=+pp`

We log debug statements during shape inference so we can maybe take a closer look at what send or recv it is stuck on

**Comment by rakkit** [comment]
Thanks a lot @H-Huang for the tips, I ran the above warmup a few times and it did not solve the PP hangs problem.  Here are the logs of PP.  (debug model, layer=8, dim=256,  BS=8;SEQ_LEN=1024;PP_micro_BS=1)  On 2x4H100, PP=2 and FSDP=4

logs on first nodes
```
[rank0]:[rank0]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime
[rank1]:[rank1]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime
[rank2]:[rank2]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime
[rank3]:[rank3]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime


[rank0]:[rank0]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank2]:[rank2]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank3]:[rank3]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`


[rank0]:[rank0]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank0]:[rank0]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank2]:[rank2]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank2]:[rank2]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank3]:[rank3]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank3]:[rank3]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1

[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 1, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send_bwd_recv, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16), P2POp(irecv pg=1, group_src=1, group_dst=0,  torch.Size([1, 1024, 256]), torch.bfloat16)]

[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 1, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send_bwd_recv, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16), P2POp(irecv pg=1, group_src=1, group_dst=0,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank0]:[rank0]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime
[rank1]:[rank1]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime
[rank2]:[rank2]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime
[rank3]:[rank3]:V0731 00:44:16 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=0, self.is_first=True, self.is_last=False, self.num_stages=2,  running shape-inference at runtime


[rank0]:[rank0]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank2]:[rank2]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank3]:[rank3]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`


[rank0]:[rank0]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank0]:[rank0]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank2]:[rank2]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank2]:[rank2]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank3]:[rank3]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank3]:[rank3]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1

[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 1, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank0]:[rank0]:V0731 00:44:23 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send_bwd_recv, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16), P2POp(irecv pg=1, group_src=1, group_dst=0,  torch.Size([1, 1024, 256]), torch.bfloat16)]

[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 1, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:44:18 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send_bwd_recv, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16), P2POp(irecv pg=1, group_src=1, group_dst=0,  torch.Size([1, 1024, 256]), torch.bfloat16)]
```


and logs on the second nodes

```
[rank0]:[rank4]:V0731 00:44:22.510000  */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=1, self.is_first=False, self.is_last=True, self.num_stages=2,  running shape-inference at runtime
[rank1]:[rank5]:V0731 00:44:16.821000  */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=1, self.is_first=False, self.is_last=True, self.num_stages=2,  running shape-inference at runtime
[rank2]:[rank6]:V0731 00:44:16.832000  */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=1, self.is_first=False, self.is_last=True, self.num_stages=2,  running shape-inference at runtime
[rank3]:[rank7]:V0731 00:44:16.866000  */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=1, self.is_first=False, self.is_last=True, self.num_stages=2,  running shape-inference at runtime



[rank0]:[rank4]:V0731 00:44:23.707000  */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 1 receiving from stage 0
[rank1]:[rank5]:V0731 00:44:18.028000  */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 1 receiving from stage 0
[rank2]:[rank6]:V0731 00:44:18.104000  */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 1 receiving from stage 0
[rank3]:[rank7]:V0731 00:44:18.032000  */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 1 receiving from stage 0
```

then it hangs forever,

**Comment by rakkit** [comment]
And here are the logs for (debug model, layer=8, dim=256, BS=8; SEQ_LEN=1024; PP_micro_BS=1) 
On 2x4H100, PP=4 and FSDP=2, it directly throws the error.
first nodes 
```

[rank0]:[rank0]:V0731 00:56:29.062000 132351 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank1]:[rank1]:V0731 00:56:29.088000 132352 */torch/distributed/pipelining/stage.py:1344] Shape inference: stage 0 skipping recv, because shape info passed in via `args`
[rank2]:[rank2]:V0731 00:56:29.059000 132353 */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 1 receiving from stage 0
[rank3]:[rank3]:V0731 00:56:29.066000 132354 */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 1 receiving from stage 0

[rank0]:[rank0]:V0731 00:56:29.326000 132351 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank0]:[rank0]:V0731 00:56:29.327000 132351 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank1]:[rank1]:V0731 00:56:29.324000 132352 */torch/distributed/pipelining/stage.py:1392] Shape inference: stage 0 inputs (tensor(..., device='meta', size=(1, 1024), dtype=torch.int64),), outputs (tensor(..., device='meta', size=(1, 1024, 256), dtype=torch.bfloat16),)
[rank1]:[rank1]:V0731 00:56:29.325000 132352 */torch/distributed/pipelining/stage.py:1419] Shape inference: stage 0 sending to stage 1
[rank3]:[rank3]: Traceback (most recent call last):
[rank3]:[rank3]:   File "/torchtitan/torchtitan/train.py", line 726, in <module>
[rank3]:[rank3]:     trainer.train()
[rank3]:[rank3]:   File "/*/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
[rank3]:[rank3]:     return f(*args, **kwargs)
[rank3]:[rank3]:            ^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/torchtitan/torchtitan/train.py", line 667, in train
[rank3]:[rank3]:     self.train_step(data_iterator)
[rank3]:[rank3]:   File "/torchtitan/torchtitan/train.py", line 568, in train_step
[rank3]:[rank3]:     loss, aux_loss = self.forward_backward_step(input_dict, labels)
[rank3]:[rank3]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/torchtitan/torchtitan/train.py", line 526, in forward_backward_step
[rank3]:[rank3]:     self.pp_schedule.step(target=targets, losses=losses)
[rank3]:[rank3]:   File "/*/torch/distributed/pipelining/schedules.py", line 512, in step
[rank3]:[rank3]:     self._step_microbatches(args_split, kwargs_split, targets_split, losses)

[rank3]:[rank3]:   File "/*/torch/distributed/pipelining/schedules.py", line 686, in _step_microbatches
[rank3]:[rank3]:     self._initialize_stage(arg_mbs[0], kwarg_mbs[0])
[rank3]:[rank3]:   File "/*/torch/distributed/pipelining/schedules.py", line 482, in _initialize_stage
[rank3]:[rank3]:     self._stage._prepare_forward_infra(self._n_microbatches, args, kwargs)
[rank3]:[rank3]:   File "/*/torch/distributed/pipelining/stage.py", line 1448, in _prepare_forward_infra
[rank3]:[rank3]:     outputs = self._shape_inference(args, kwargs)
[rank3]:[rank3]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/*/torch/distributed/pipelining/stage.py", line 1359, in _shape_inference
[rank3]:[rank3]:     dist.recv_object_list(
[rank3]:[rank3]:   File "/*/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank3]:[rank3]:     return func(*args, **kwargs)
[rank3]:[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/*/torch/distributed/distributed_c10d.py", line 3362, in recv_object_list
[rank3]:[rank3]:     rank_sizes = recv(object_sizes_tensor, src=src, group=group, group_src=group_src)
[rank3]:[rank3]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/*/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank3]:[rank3]:     return func(*args, **kwargs)
[rank3]:[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/*/torch/distributed/distributed_c10d.py", line 2466, in recv
[rank3]:[rank3]:     work = irecv(tensor, src=src, group=group, tag=tag, group_src=group_src)
[rank3]:[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]:   File "/*/torch/distributed/distributed_c10d.py", line 2404, in irecv
[rank3]:[rank3]:     return group.recv([tensor], group_src, tag)
[rank3]:[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:[rank3]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
[rank3]:[rank3]: ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
[rank3]:[rank3]: Last error:
[rank3]:[rank3]: socketPollConnect: Connect to 10.14.0.142<50097> failed : Connection reset by peer
[rank1]:[rank1]:V0731 00:56:29.427000 132352 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 0, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:56:29.428000 132352 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:56:29.428000 132352 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank1]:[rank1]:V0731 00:56:29.431000 132352 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 1, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:56:29.431000 132352 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:56:29.431000 132352 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank1]:[rank1]:V0731 00:56:29.435000 132352 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 2, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:56:29.436000 132352 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:56:29.436000 132352 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16)]
[rank1]:[rank1]:V0731 00:56:29.438000 132352 */torch/distributed/pipelining/stage.py:733] [Stage 0] Forwarded chunk 3, outputs: Tensor(torch.Size([1, 1024, 256]), grad=True, dtype=torch.bfloat16)
[rank1]:[rank1]:V0731 00:56:29.439000 132352 */torch/distributed/pipelining/stage.py:448] [Stage 0] Sending tensor to Stage 1: torch.Size([1, 1024, 256])
[rank1]:[rank1]:V0731 00:56:29.439000 132352 */torch/distributed/pipelining/schedules.py:407] batch_p2p fwd_send_bwd_recv, [P2POp(isend pg=1, group_src=0, group_dst=1,  torch.Size([1, 1024, 256]), torch.bfloat16), P2POp(irecv pg=1, group_src=1, group_dst=0,  torch.Size([1, 1024, 256]), torch.bfloat16)]

```


and the second node
```
[rank0]:[rank4]:V0731 00:56:28.929000 3080918 */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 2 receiving from stage 1
[rank1]:[rank5]:V0731 00:56:29.001000 3080919 */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 2 receiving from stage 1
[rank3]:[rank7]:V0731 00:56:27.816000 3080921 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=3, self.is_first=False, self.is_last=True, self.num_stages=4,  running shape-inference at runtime
[rank3]:[rank7]:V0731 00:56:28.975000 3080921 */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 3 receiving from stage 2
[rank2]:[rank6]:V0731 00:56:33.510000 3080920 */torch/distributed/pipelining/stage.py:1326] Finished pipeline stage init, self.stage_index=3, self.is_first=False, self.is_last=True, self.num_stages=4,  running shape-inference at runtime
[rank2]:[rank6]:V0731 00:56:34.651000 3080920 */torch/distributed/pipelining/stage.py:1354] Shape inference: stage 3 receiving from stage 2


[rank0]:[rank4]:[W731 01:01:29.544034999 socket.cpp:460] [c10d] waitForInput: poll for socket SocketImpl(fd=49, addr=jrc0913.jureca:46374, remote=jrc0912.jureca:38293) returned 0, likely a timeout
[rank0]:[rank4]:[W731 01:01:29.544127925 socket.cpp:485] [c10d] waitForInput: socket SocketImpl(fd=49, addr=jrc0913.jureca:46374, remote=jrc0912.jureca:38293) timed out after 300000ms
[rank1]:[rank5]:[W731 01:01:29.626081528 socket.cpp:460] [c10d] waitForInput: poll for socket SocketImpl(fd=73, addr=jrc0913.jureca:46390, remote=jrc0912.jureca:38293) returned 0, likely a timeout
[rank1]:[rank5]:[W731 01:01:29.626166657 socket.cpp:485] [c10d] waitForInput: socket SocketImpl(fd=73, addr=jrc0913.jureca:46390, remote=jrc0912.jureca:38293) timed out after 300000ms
[rank2]:[rank6]:[W731 01:01:34.268735182 socket.cpp:460] [c10d] waitForInput: poll for socket SocketImpl(fd=73, addr=jrc0913.jureca:46398, remote=jrc0912.jureca:38293) returned 0, likely a timeout
[rank2]:[rank6]:[W731 01:01:34.268830146 socket.cpp:485] [c10d] waitForInput: socket SocketImpl(fd=73, addr=jrc0913.jureca:46398, remote=jrc0912.jureca:38293) timed out after 300000ms
[rank3]:[rank7]:[W731 01:01:29.544130038 socket.cpp:460] [c10d] waitForInput: poll for socket SocketImpl(fd=73, addr=jrc0913.jureca:46404, remote=jrc0912.jureca:38293) returned 0, likely a timeout
[rank3]:[rank7]:[W731 01:01:29.544217341 socket.cpp:485] [c10d] waitForInput: socket SocketImpl(fd=73, addr=jrc0913.jureca:46404, remote=jrc0912.jureca:38293) timed out after 300000ms
[rank1]:[rank5]: Traceback (most recent call last):
[rank1]:[rank5]:   File "/torchtitan/torchtitan/train.py", line 726, in <module>
[rank1]:[rank5]:     trainer.train()
[rank1]:[rank5]:   File "/*/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
[rank1]:[rank5]:     return f(*args, **kwargs)
[rank1]:[rank5]:            ^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/torchtitan/torchtitan/train.py", line 667, in train
[rank1]:[rank5]:     self.train_step(data_iterator)
[rank1]:[rank5]:   File "/torchtitan/torchtitan/train.py", line 568, in train_step
[rank1]:[rank5]:     loss, aux_loss = self.forward_backward_step(input_dict, labels)
[rank1]:[rank5]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/torchtitan/torchtitan/train.py", line 526, in forward_backward_step
[rank1]:[rank5]:     self.pp_schedule.step(target=targets, losses=losses)
[rank1]:[rank5]:   File "/*/torch/distributed/pipelining/schedules.py", line 512, in step
[rank1]:[rank5]:     self._step_microbatches(args_split, kwargs_split, targets_split, losses)
[rank1]:[rank5]:   File "/*/torch/distributed/pipelining/schedules.py", line 686, in _step_microbatches
[rank1]:[rank5]:     self._initialize_stage(arg_mbs[0], kwarg_mbs[0])
[rank1]:[rank5]:   File "/*/torch/distributed/pipelining/schedules.py", line 482, in _initialize_stage
[rank1]:[rank5]:     self._stage._prepare_forward_infra(self._n_microbatches, args, kwargs)
[rank1]:[rank5]:   File "/*/torch/distributed/pipelining/stage.py", line 1448, in _prepare_forward_infra
[rank1]:[rank5]:     outputs = self._shape_inference(args, kwargs)
[rank1]:[rank5]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/*/torch/distributed/pipelining/stage.py", line 1359, in _shape_inference
[rank1]:[rank5]:     dist.recv_object_list(
[rank1]:[rank5]:   File "/*/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank1]:[rank5]:     return func(*args, **kwargs)
[rank1]:[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/*/torch/distributed/distributed_c10d.py", line 3362, in recv_object_list
[rank1]:[rank5]:     rank_sizes = recv(object_sizes_tensor, src=src, group=group, group_src=group_src)
[rank1]:[rank5]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/*/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank1]:[rank5]:     return func(*args, **kwargs)
[rank1]:[rank5]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/*/torch/distributed/distributed_c10d.py", line 2466, in recv
[rank1]:[rank5]:     work = irecv(tensor, src=src, group=group, tag=tag, group_src=group_src)
[rank1]:[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]:   File "/*/torch/distributed/distributed_c10d.py", line 2404, in irecv
[rank1]:[rank5]:     return group.recv([tensor], group_src, tag)
[rank1]:[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:[rank5]: torch.distributed.DistBackendError: [2] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '1:2', but store->get('1:2') got error: wait timeout after 300000ms, keys: /default_pg/0//1//1:2
```

**Comment by H-Huang** [comment]
The second set of logs does seem to suggest a host misconfiguration error, not sure if `NCCL_DEBUG=INFO` will provide more useful information:

```
[rank3]:[rank3]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.26.2
[rank3]:[rank3]: ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
[rank3]:[rank3]: Last error:
[rank3]:[rank3]: socketPollConnect: Connect to 10.14.0.142<50097> failed : Connection reset by peer
```

> I ran the above warmup a few times and it did not solve the PP hangs problem

Curious, after running the warmup was that able to run and then it hang on the shape inference part? That would be super strange. Or did the warmup just hang as well.

**Comment by rakkit** [comment]
@H-Huang the warmup itself works well.  I remember when I checked the NCCL's log, it did not tell anything useful for the second example, as it raises an error and immediately fails.  I would if the forward  (`self.submod(*args, **kwargs)`) in the early stages affects the send/recv? 

@tianyu-l  I can also confirm explicitly passing the input/output shape in `PipelineStage` can skip this problem (so the problem seems, really come from stage init).    It's kind ok for transformers, we need to pass extra args in `pipeline_module_split `, with (pp-micro bs, seqlen, model dimension, and Vocab size after padding), and maybe dtype in case of any middle activation is not BF16

**Comment by H-Huang** [comment]
> I would if the forward (self.submod(*args, **kwargs)) in the early stages affects the send/recv?

OH I realized that you are using MoE? If so, does that mean during the model forward that it is doing extra communication or is expert parallel involved? Basically in shape inference we do a dry-run of the model forward for each stage, but if there is communication during forward that might lead to a hang.

Can you paste your .toml config file? Would like to see if I can repro

**Comment by rakkit** [comment]
Nope, both test is based on dense llama, given FSDP=2 or 4, there will be an all-gather anyhow 
`self.submod(*args, **kwargs)` is trigered in `_shape_inference` 
(stage.py)[https://github.com/pytorch/pytorch/blob/v2.7.0/torch/distributed/pipelining/stage.py#L1379]

For reproduce, its (debugmodel)[https://github.com/pytorch/torchtitan/blob/main/torchtitan/models/llama3/train_configs/debug_model.toml],  2 nodes each with 4 gpus, {FSDP=2, PP=4} or {FSDP=4, PP=2}

**Comment by H-Huang** [comment]
Quick update: I was investigating this on the machines I had available (PyTorch nightly / Cuda 12.4 / NCCL 2.25.1) and I was running into a hang during the schedule execution rather than `shape_inference`.

However, when I used the environment `TORCH_DISTRIBUTED_DEBUG=DETAIL`, the hang disappears. Since distributed_debug adds synchronization points to collectives maybe one hypothesis is there is a race condition in `_shape_inference` that also affects the schedule execution. I'm still not sure and am looking into it

**Comment by rakkit** [comment]
Thanks @H-Huang for what I have been tested torch[2.6, 2.7] x cuda [12.6, 12.8] I always stuck at `shape_inference` and cannot go further, so I dont know if I will have a problem in schedule execution. 

I am leaving for vacation and will come back later next week.   I have a commit [here](https://github.com/rakkit/torchtitan/commit/95732cac15e3c48983328961210b9e0b61e02b1d#diff-1b96a47cc45205fa2f1ac4bc5e1194160cb6c705607ef3c968c4f13b9002afc1) that manually calculates the input and output shape can temporarily fix the problem on the torchtitan side without bothering the PyTorch code.
It obviously works for the transformer (LLM) only.

The basic logic is 

1. first stage always takes `(pp_mbs, seq_len)` as input.

2. The output of the first stage, the input-output of the mid stages, and the input of the last stage is always  `(pp_mbs, tp_seq_len, dim)`.  Here we assume `TP` always does SeqParallel that `tp_seq_len=seq_len/tp`

3. The output of the last stage is `(pp_mbs, seq_len, vocab_size)`, (i did not get why TP loss parallel does not matter here).

We have BF16 by default, but in some weird cases, like DDP only or only (TP+PP) we fail into FP32 dtype. 

and we better to put it to `meta` device otherwise we get werid error of device not matched.

**Comment by wconstab** [comment]
@H-Huang  could you share a flight-recorder trace and a debug log from the hanging job? maybe also put a .barrier() after shape-inference, partly to make it clear on the FR trace where the shape-inference ends and the step() begins.  It should be possible to figure out if any p2p mismatches are occurring just by looking at the dumped traces.

**Comment by H-Huang** [comment]
Hi @rakkit, this PR https://github.com/pytorch/pytorch/pull/160210 was able to fix the issue for our runs internally, but I'm not sure if it will fix your issue. It just forces the initialization of the nccl communicators that are going to be used in the schedule execution run. Maybe you can try this change as well: https://github.com/pytorch/pytorch/pull/160342, so that all the ops used in `shape_inference` are also batch_p2p_ops. 

Something that helped me debug the hangs was to get the flight recorder dumps (https://docs.pytorch.org/tutorials/unstable/flight_recorder_tutorial.html) then call `torchfrtrace <dump_folder> -j --allow-incomplete-ranks`. This let me see what collectives the ranks were stuck in. If you are able to get these dumps and link them that would be helpful to debug your issue as well.

Example flight recorder output:

<img width="1360" height="351" alt="Image" src="https://github.com/user-attachments/assets/afd0a90a-d952-44c3-b630-798ed66f89fd" />

**Comment by janEbert** [comment]
Sorry for the commit-mention spam, I wasn't aware each rebase+force-push was causing a new GitHub mention. I've added a word joiner character to prevent GitHub parsing the link to this issue.

**Comment by tianyu-l** [comment]
@rakkit @janEbert could you confirm if PR https://github.com/pytorch/pytorch/pull/160210 fixes the PP hang? If so, we can close the issue.

**Comment by rakkit** [comment]
@tianyu-l Confirm testing on 2 nodes 2x4 GPUS,  (PP=2, FSDP=4), (PP=4, FSDP=2), (PP=2, TP=2, FSDP=2) works now
