### ISSUE TITLE
Nan's on step 1  of 405B model training

### ISSUE THREAD

**Issue by githubsgi** [pytorch/torchtitan#951]
Anyone has any tip of how to  debug/prevent nan's  on step 1  during FSDP+TP training of the 405B model on 256 GPU's on the C4 dataset ?

**Comment by fegin** [comment]
Can you start with FSDP to isolate the problem and try to disable or change some optimizations (e.g., Selective AC -> No AC -> Full AC) if OOM doesn't occur?

**Comment by lessw2020** [comment]
Hi @githubsgi ,
Are you finding the nans show consistently?  I.e. you restart and retry and hit it again? 

1 - If so, you can export this env variable:
export TORCH_NCCL_NAN_CHECK=1
This will trigger an automatic NaN check on all outgoing collectives and will force an assert if one is detected and will show the rank and node that triggered it.  From there, inspect the node directly (or flag and exclude it). 
The one time I was consistently hitting Nans on training runs I used this and we found that a gpu was emitting an XID...after rebooting that GPU, the Nans went away.  You can turn it off after the Nans are resolved.

2 - It's not possible to run 405B with only FSDP, so you'll have to use 2D of some form.  You could try replacing TP with context parallel but since I've run both already, I think it's much more likely you are hitting a hardware issue.  
*I literally just launched 2 jobs at 256 gpu scale to run 405B exactly as you are doing, and used both AsyncTP and CP...both are running fine as expected. 

3 - Lastly, make sure you are not running your GPUs at say 95% or higher b/c then you are likely triggering cuda Cache retries and this I have seen before can sometimes be linked to Nans.  Thus cut your batch size to 1 if needed and try that. 

Anyway, I literally just ran 2 jobs as you are doing (256 and 405B, TP and CP) and both are running fine...thus I would try points 1 and 3 above.

**Comment by fegin** [comment]
> 3 - Lastly, make sure you are not running your GPUs at say 95% or higher b/c then you are likely triggering cuda Cache retries and this I have seen before can sometimes be linked to Nans. Thus cut your batch size to 1 if needed and try that.

This is interesting. I have seen OOM or hang before. I don't know the memory pressure can lead to NaN. TIL.

**Comment by awgu** [comment]
I think allocator retries should not affect numerics.

**Comment by lessw2020** [comment]
I agree. To be clear my point 3 about allocator retries is anecdotal and is only something I've seen very occasionally at large scale. It could just be xid errors that happened at same time.

**Comment by lessw2020** [comment]
just for reference, 4 runs with a variety of settings at 256 scale with 405B, no Nans.  Thus most likely this is hardware specific and recommend trying out the the Nan checker as first step. 

<img width="433" alt="Image" src="https://github.com/user-attachments/assets/c0378cb4-f983-41e7-869c-c98dd40ca992" />

**Comment by githubsgi** [comment]
Thanks for the tips.  Let me try them to root cause the Nan issue. A few quick questions.  In the trace above, what was the batch size used. ?  How long did it take to reach 2.5K steps ?  What GPUs were used ?

**Comment by lessw2020** [comment]
in the above I was using bs=2 with AC = full.  Note that this is on H200 which have higher HBM than H100 and I could have gone higher on bs...my goal was just get the runs going so they could go overnight to prove out no Nans, and replicate what should fit on an H100.
run time was approx 14 hours for 3K steps.

**Comment by githubsgi** [comment]
@lessw2020  , still investigating the nan issue.  Adding TP a appears to cause Nan.     Another question out of curiosity,  how much MFU were you getting in the run  above ?

**Comment by lessw2020** [comment]
Hi @githubsgi  - nice, glad to hear this is resolved for you.  Just curious but what was the underlying issue? 
re: MFU - between 37 - 40% MFU depending on exact config. 
But note - this is on H200, not H100.

**Comment by githubsgi** [comment]
@lessw2020 , thanks. It was a ccl version issue.  It is also on a non-cuda GPU cluster.

**Comment by lessw2020** [comment]
@githubsgi  - thanks for the update on the root issue and glad you were able to get it resolved!
